theme: minima

header_pages:
  - index.md
  - about.md
  - portfolio.md
  - contact.md

custom_css: /assets/css/style.css

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

paginate: 0
show_posts: false

title: Alexis
description: Cartography and Data Visualization









